import json
import logging
from abc import ABC, abstractmethod
from typing import List, Dict, Any
from datetime import datetime

logger = logging.getLogger("OASIS.ERPAdapter")

# =====================================================================
# Standardized Internal Schemas
# =====================================================================

class TransferRequest:
    """Internal standardized schema for inter-branch transfers."""
    def __init__(self, from_org_cd: str, to_org_cd: str, items: List[Dict[str, Any]], requested_by: str = "AI_EMPLOYEE"):
        self.transfer_id = f"TRF-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        self.from_org_cd = from_org_cd
        self.to_org_cd = to_org_cd
        self.items = items  # List of {"item_code": str, "qty": float, "value": float}
        self.requested_by = requested_by
        self.timestamp = datetime.now().isoformat()

class PurchaseOrderRequest:
    """Internal standardized schema for supplier purchase orders."""
    def __init__(self, org_cd: str, supplier_cd: str, items: List[Dict[str, Any]], requested_by: str = "AI_EMPLOYEE"):
        self.po_id = f"PO-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        self.org_cd = org_cd
        self.supplier_cd = supplier_cd
        self.items = items  # List of {"item_code": str, "qty": float, "unit_cost": float}
        self.requested_by = requested_by
        self.timestamp = datetime.now().isoformat()

# =====================================================================
# Base ERP Adapter Interface
# =====================================================================

class BaseERPAdapter(ABC):
    """
    The Unified ERP Ingestion and Action Layer.
    All Premium Connectors (Zoho, Tally, Sage) must inherit from this.
    """
    def __init__(self, tenant_id: str, credentials: Dict[str, str]):
        self.tenant_id = tenant_id
        self.credentials = credentials
        
    @abstractmethod
    def fetch_inventory_snapshot(self) -> List[Dict[str, Any]]:
        """Ingestion Layer: Pulls current stock levels into O.A.S.I.S format."""
        pass

    @abstractmethod
    def push_purchase_order(self, po: PurchaseOrderRequest) -> bool:
        """Action Layer: Converts internal PO schema to ERP-specific API call."""
        pass

    @abstractmethod
    def push_transfer_order(self, trf: TransferRequest) -> bool:
        """Action Layer: Converts internal Transfer schema to ERP-specific API call."""
        pass

# =====================================================================
# Zoho Inventory Adapter (Proof of Concept)
# =====================================================================

class ZohoAdapter(BaseERPAdapter):
    """Zoho Premium Connector"""
    
    def fetch_inventory_snapshot(self) -> List[Dict[str, Any]]:
        # In a real implementation, this makes a requests.get() to Zoho Inventory API
        logger.info(f"[ZOHO] Fetching inventory for tenant {self.tenant_id}...")
        return []

    def push_purchase_order(self, po: PurchaseOrderRequest) -> bool:
        # Translate to Zoho JSON format
        zoho_payload = {
            "vendor_id": po.supplier_cd, # Assuming mapped
            "date": po.timestamp[:10],
            "line_items": [
                {
                    "item_id": item["item_code"], 
                    "rate": item["unit_cost"], 
                    "quantity": item["qty"]
                } for item in po.items
            ],
            "notes": f"Auto-generated by O.A.S.I.S. AI Employee (Req: {po.requested_by})"
        }
        logger.info(f"[ZOHO] Pushing PO {po.po_id}: {json.dumps(zoho_payload)[:100]}...")
        # requests.post("https://inventory.zoho.com/api/v1/purchaseorders", json=zoho_payload, headers=...)
        return True

    def push_transfer_order(self, trf: TransferRequest) -> bool:
        logger.info(f"[ZOHO] Pushing Transfer {trf.transfer_id} from {trf.from_org_cd} to {trf.to_org_cd}")
        return True

# =====================================================================
# Tally TDL Adapter (Proof of Concept)
# =====================================================================

class TallyAdapter(BaseERPAdapter):
    """Tally ERP 9 / Tally Prime Connector via XML TDL"""
    
    def fetch_inventory_snapshot(self) -> List[Dict[str, Any]]:
        logger.info(f"[TALLY] Fetching inventory for tenant {self.tenant_id} via TDL XML...")
        return []

    def push_purchase_order(self, po: PurchaseOrderRequest) -> bool:
        # Translate to Tally XML
        tally_xml = f"""
        <ENVELOPE>
            <HEADER>
                <TALLYREQUEST>Import Data</TALLYREQUEST>
            </HEADER>
            <BODY>
                <IMPORTDATA>
                    <REQUESTDESC>
                        <REPORTNAME>Vouchers</REPORTNAME>
                    </REQUESTDESC>
                    <REQUESTDATA>
                        <TALLYMESSAGE xmlns:UDF="TallyUDF">
                            <VOUCHER VCHTYPE="Purchase Order" ACTION="Create">
                                <PARTYLEDGERNAME>{po.supplier_cd}</PARTYLEDGERNAME>
                                <!-- Line items omitted for brevity -->
                            </VOUCHER>
                        </TALLYMESSAGE>
                    </REQUESTDATA>
                </IMPORTDATA>
            </BODY>
        </ENVELOPE>
        """
        logger.info(f"[TALLY] Pushing PO {po.po_id} via XML...")
        return True

    def push_transfer_order(self, trf: TransferRequest) -> bool:
        logger.info(f"[TALLY] Pushing Transfer {trf.transfer_id} (Stock Journal Voucher)")
        return True
