import os
import json
from datetime import datetime
import logging
from typing import Dict, Any, List, Optional

logger = logging.getLogger(__name__)

class ObsidianMixin:
    """
    Bridge mixin for O.A.S.I.S. to push data into the Obsidian Second Brain using
    a relational schema (linked entities) for neural network discoverability.
    """
    
    def __init__(self, vault_path: str = None):
        self.vault_path = vault_path or r"C:\Users\iLink\.gemini\antigravity\scratch\oasis\Oasis"
        # Ensure relational directories exist
        for folder in ["Runs", "Entities/Stores", "Entities/Suppliers", "Entities/Products", "Neural_Archive", "Simulations"]:
            os.makedirs(os.path.join(self.vault_path, folder), exist_ok=True)

    def _format_link(self, entity_type: str, entity_id: str) -> str:
        """Helper to format Obsidian links, e.g., [[Store_Rhapta]]."""
        if not entity_id or str(entity_id).upper() == 'UNKNOWN':
             return "[[Unknown]]"
        safe_id = str(entity_id).strip().replace(" ", "_").replace("[", "").replace("]", "")
        return f"[[{entity_type}_{safe_id}]]"

    def _ensure_entity_note(self, entity_type: str, entity_id: str, metadata: Dict[str, Any] = None):
        """Creates/updates basic entity notes (Stores, Suppliers) with relationship links."""
        if not entity_id or str(entity_id).upper() == 'UNKNOWN': return
        
        safe_id = str(entity_id).strip().replace(" ", "_").replace("[", "").replace("]", "")
        folder = f"Entities/{entity_type}s"
        file_path = os.path.join(self.vault_path, folder, f"{entity_type}_{safe_id}.md")
        
        if not os.path.exists(file_path):
            logger.info(f"Creating new entity note for {entity_type}: {entity_id}")
            content = f"""# {entity_type}: {entity_id}
type:: #entity/{entity_type.lower()}
id:: {entity_id}

## 🔗 Relationships
- **Affiliated Runs**: #run/history
- **Neural Connections**: #neural/node

## 📉 Historical Performance
- To be populated by simulation insights.
"""
            if metadata:
                 for k, v in metadata.items():
                      content += f"{k}:: {v}\n"
                      
            with open(file_path, "w", encoding='utf-8') as f:
                f.write(content)

    def log_run_summary(self, summary_data: dict):
        """Logs a relational replenishment run summary to the vault."""
        timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
        store_id = summary_data.get('store_id', 'Unknown')
        supplier = summary_data.get('supplier_name', 'General')
        
        # Ensure entity notes exist for links
        self._ensure_entity_note("Store", store_id)
        self._ensure_entity_note("Supplier", supplier)
        
        store_link = self._format_link("Store", store_id)
        supplier_link = self._format_link("Supplier", supplier)
        
        file_path = os.path.join(self.vault_path, "Runs", f"{timestamp}_Summary.md")
        
        content = f"""# replenishment Run Summary: {timestamp}
- **Store**: {store_link}
- **Supplier**: {supplier_link}
- **Mode**: {summary_data.get('mode', 'N/A')}
- **Total Products**: {summary_data.get('total_products', 0)}
- **Total Units**: {summary_data.get('total_units', 0)}
- **Total Cost**: KES {summary_data.get('total_cost', 0.0):,.2f}
- **Total Value**: KES {summary_data.get('total_value', 0.0):,.2f}
- **Est. Savings**: KES {summary_data.get('est_savings', 0.0):,.2f}

## 🧠 Neural Relationship
This run links {store_link} to {supplier_link}.
- **Neural Link ID**: [[Neural_Archive/Run_{timestamp}]]

## 🔍 Key Insights
{summary_data.get('insights', 'No specific insights recorded.')}

---
Generated by O.A.S.I.S. Relational Bridge (v10.1)
"""
        with open(file_path, "w", encoding='utf-8') as f:
            f.write(content)
        
        # v10.1: Transition from CSV to Relational Neural Archive
        self.append_to_relational_archive(summary_data, timestamp)

    def append_to_relational_archive(self, data: dict, timestamp: str):
        """Creates a relational markdown entry for neural network consumption (Dataview compatible)."""
        store_id = data.get('store_id', 'Unknown')
        supplier = data.get('supplier_name', 'General')
        
        file_path = os.path.join(self.vault_path, "Neural_Archive", f"Run_{timestamp}.md")
        
        content = f"""# Neural Run Entry: {timestamp}
type:: #neural/run
timestamp:: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
store:: {self._format_link("Store", store_id)}
supplier:: {self._format_link("Supplier", supplier)}
mode:: {data.get('mode', 'N/A')}
products:: {data.get('total_products', 0)}
units:: {data.get('total_units', 0)}
cost:: {data.get('total_cost', 0.0)}
value:: {data.get('total_value', 0.0)}
savings:: {data.get('est_savings', 0.0)}

## 🧠 Relationship Discovery
- **Store Context**: Linked to {self._format_link("Store", store_id)} history.
- **Supplier Context**: Tied to {self._format_link("Supplier", supplier)} reliability.
"""
        with open(file_path, "w", encoding='utf-8') as f:
            f.write(content)
        logger.info(f"Relational data logged to Neural Archive: {file_path}")

    def log_simulation_trace(self, tier_name: str, logs: list):
        """Logs simulation trace data with relational links to tiers."""
        timestamp = datetime.now().strftime("%Y-%m-%d_%H%M")
        file_path = os.path.join(self.vault_path, "Simulations", f"{tier_name}_{timestamp}_Trace.md")
        
        avg_fill = sum(l.fill_rate for l in logs) / len(logs) if logs else 0
        
        content = f"""# Simulation Trace: {tier_name} ({timestamp})
- **Tier**: [[{tier_name}]]
- **Avg Fill Rate**: {avg_fill:.1f}%
- **Days Simulated**: {len(logs)}

## 📉 Daily Performance
| Day | Fill Rate | Stockouts | Inventory Value |
|-----|-----------|-----------|-----------------|
"""
        for l in logs[:30]: 
            content += f"| {l.day} | {l.fill_rate:.1f}% | {l.stockout_count} | {l.inventory_value:,.0f} |\n"

        with open(file_path, "w", encoding='utf-8') as f:
            f.write(content)
        logger.info(f"Simulation trace logged to Obsidian: {file_path}")
