import os
import json
import logging
import pandas as pd
from datetime import datetime, timedelta
from typing import Dict, Any, List

from .daily_pipeline import DailyPipeline
from .shadow_mode import ShadowModeEngine
from .extrapolate_stock import run_extrapolation

logger = logging.getLogger("OASIS.Simulation")

class SimulationEngine:
    """
    Runs a multi-day simulation by replaying history.
    For each day:
    1. Reconstructs Stock On Hand (SOH) using Extrapolator.
    2. Runs DailyPipeline (AI Recommendations).
    3. Matches against real human GRNs for that date.
    4. Records performance metrics.
    """
    
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.data_dir = config.get('data_dir', '.')
        self.results_dir = os.path.join(self.data_dir, 'simulation_reports')
        os.makedirs(self.results_dir, exist_ok=True)
        
    def run_simulation(self, start_date_str: str, end_date_str: str):
        start_date = datetime.strptime(start_date_str, "%Y-%m-%d")
        end_date = datetime.strptime(end_date_str, "%Y-%m-%d")
        
        current_date = start_date
        all_daily_stats = []
        
        simulation_id = datetime.now().strftime('%Y%m%d_%H%M%S')
        logger.info(f"===== STARTING SIMULATION: {simulation_id} ({start_date_str} to {end_date_str}) =====")
        
        while current_date <= end_date:
            date_str = current_date.strftime("%Y-%m-%d")
            logger.info(f"--- Simulating Date: {date_str} ---")
            
            # Step 1: Stock Reconstruction (Ground Truth for the morning)
            try:
                scorecard_path = run_extrapolation(date_str, self.data_dir)
            except Exception as e:
                logger.error(f"Stock reconstruction failed for {date_str}: {e}")
                current_date += timedelta(days=1)
                continue
                
            # Step 2: Run AI Pipeline
            daily_config = self.config.copy()
            daily_config['scorecard_path'] = scorecard_path
            daily_config['shadow_mode'] = True # Always shadow in simulation
            
            pipeline = DailyPipeline(daily_config)
            pipeline_result = pipeline.run_daily_cycle()
            
            # Step 3: Match against Real Human GRNs for THIS date
            # We need to find the Shadow PO generated by the pipeline
            po_path = None
            for step in pipeline_result.get('steps', []):
                if step['step'] == 'APPROVAL_QUEUE' and step['status'] == 'OK':
                    # Extract path from detail or re-construct
                    po_path = os.path.join(self.data_dir, 'pipeline_logs', f"daily_po_{self.config.get('store_id', 'GLOBAL')}_{pipeline_result['run_id']}.csv")
                    break
            
            daily_comparison_stats = {}
            if po_path and os.path.exists(po_path):
                try:
                    engine = ShadowModeEngine(self.data_dir)
                    # Load AI PO
                    engine.shadow_po = pd.read_csv(po_path)
                    
                    # Ingest all human GRN files (engine handles batching)
                    grn_pattern = os.path.join(self.data_dir, "*grnd*.xlsx")
                    import glob
                    grn_files = glob.glob(grn_pattern)
                    
                    # Filter: Only process GRNs that happened on THIS DATE
                    # We modify ingest_human_orders logic or just pass all and let generate_comparison filter
                    engine.ingest_human_orders(grn_files)
                    
                    # Filter ingested human_po to ONLY current_date
                    if not engine.human_po.empty:
                        engine.human_po['GRN Date'] = pd.to_datetime(engine.human_po['GRN Date'], errors='coerce')
                        engine.human_po = engine.human_po[engine.human_po['GRN Date'].dt.date == current_date.date()]
                    
                    comparison = engine.generate_comparison()
                    daily_comparison_stats = engine.get_summary_stats()
                except Exception as e:
                    logger.error(f"Divergence matching failed for {date_str}: {e}")
            
            # Record result
            day_record = {
                'date': date_str,
                'pipeline_status': pipeline_result['status'],
                'comparison': daily_comparison_stats
            }
            all_daily_stats.append(day_record)
            
            current_date += timedelta(days=1)
            
        # Final Aggregate Report
        report = {
            'simulation_id': simulation_id,
            'start_date': start_date_str,
            'end_date': end_date_str,
            'daily_records': all_daily_stats,
            'summary': self._aggregate_stats(all_daily_stats)
        }
        
        report_path = os.path.join(self.results_dir, f"sim_report_{simulation_id}.json")
        with open(report_path, 'w') as f:
            json.dump(report, f, indent=2)
            
        logger.info(f"===== SIMULATION COMPLETE: Report saved to {report_path} =====")
        return report

    def _aggregate_stats(self, records: List[Dict]):
        total_missed = 0
        total_over = 0
        total_aligned = 0
        total_risk = 0.0
        
        for r in records:
            comp = r.get('comparison', {})
            total_missed += comp.get('human_missed', 0)
            total_over += comp.get('human_over_ordered', 0)
            total_aligned += comp.get('aligned', 0)
            total_risk += comp.get('over_order_waste_risk', 0.0)
            
        return {
            'total_human_missed': total_missed,
            'total_human_over_ordered': total_over,
            'total_aligned': total_aligned,
            'cumulative_holding_risk': round(total_risk, 2)
        }
