import json
import os
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

# Paths
ALCOHOL_DIR = r"c:\Users\iLink\.gemini\antigravity\scratch\oasis\data\filtered_queries"

def format_currency(value):
    return f"KES {value:,.2f}"

def generate_professional_report():
    print("Generating Professional Operational Breakdown...")
    
    with open('alcohol_intel.json', 'r') as f:
        data = json.load(f)
        
    doc = Document()
    
    # 1. Title Page Style Header
    title = doc.add_heading('STRATEGIC OPERATIONAL BREAKDOWN', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    subtitle = doc.add_heading('WINE, BEER, & SPIRITS SECTION', 1)
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_paragraph(f"Generated by O.A.S.I.S. Neural Intelligence Suite\nDate: April 2, 2026")
    doc.add_paragraph("\n" + "="*50 + "\n")

    # 2. Executive Summary
    doc.add_heading('1. Executive Summary', level=1)
    doc.add_paragraph(
        "This report provides an interrogation of the Alcohol section based on the current O.A.S.I.S. neural network. "
        "The section is characterized by a high-revenue Beer sector with extreme velocity and a low-turnover, "
        "high-complexity Wine sector that represents significant inventory risk."
    )
    
    # Summary Table
    table = doc.add_table(rows=1, cols=4)
    table.style = 'Table Grid'
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'Sector'
    hdr_cells[1].text = 'SKU Count'
    hdr_cells[2].text = 'Revenue (KES)'
    hdr_cells[3].text = 'Role in Store'
    
    sectors = [
        ('BEER', data['beer_metrics']['SKU Count'], format_currency(data['beer_metrics']['Total Revenue']), 'Traffic Anchor / High Velocity'),
        ('WINES', data['wine_metrics']['SKU Count'], format_currency(data['wine_metrics']['Total Revenue']), 'Premium Variety / Low velocity'),
    ]
    
    for sect, count, rev, role in sectors:
        row_cells = table.add_row().cells
        row_cells[0].text = sect
        row_cells[1].text = str(count)
        row_cells[2].text = rev
        row_cells[3].text = role

    # 3. Beer Section: The Traffic Anchor
    doc.add_heading('2. Beer Section: Velocity & Refill Strategy', level=1)
    doc.add_paragraph(
        "Beer is the primary revenue driver for the alcohol section. The top 10 SKUs account for a disproportionate "
        "amount of the section's total cash flow. Out-of-stocks in these items represent a high 'Ghost Demand' risk."
    )
    
    doc.add_heading('Top 5 Velocity Anchors (BEER)', level=2)
    for i, item in enumerate(data['beer_pareto'][:5]):
        p = doc.add_paragraph(style='List Bullet')
        p.add_run(f"{item['SKU Name']} ").bold = True
        p.add_run(f"| Revenue: {format_currency(item['Revenue'])} | Qty: {item['Total Quantity']:,.0f}")

    doc.add_paragraph(
        "ACTION: Implement 24-hour safety stock triggers for these items. Do not wait for standard delivery windows."
    )

    # 4. Wine Section: The Complexity Bottleneck
    doc.add_heading('3. Wine Section: Catalog Optimization', level=1)
    doc.add_paragraph(
        f"The Wine section currently carries {data['wine_metrics']['SKU Count']} unique SKUs. "
        "However, the total revenue (KES {data['wine_metrics']['Total Revenue']:,.2f}) is significantly lower than Beer. "
        "This inventory profile indicates high 'Bloat'—meaning capital is tied up in slow-moving bottles."
    )
    
    doc.add_heading('The Pareto List (Top 5 Wines)', level=2)
    for i, item in enumerate(data['wine_pareto'][:5]):
        p = doc.add_paragraph(style='List Bullet')
        p.add_run(f"{item['SKU Name']} ").bold = True
        p.add_run(f"| Revenue: {format_currency(item['Revenue'])}")

    doc.add_paragraph(
        "ACTION: Recommend a 20% catalog reduction. Identify wines with zero movement over the last 90 days "
        "and clear them through bundles or cross-promotions."
    )

    # 5. Neural Affinity: The Halo Effect
    doc.add_heading('4. Neural Insights: Cross-Merchandising', level=1)
    doc.add_paragraph(
        "Our neural network tracks 'Halo Links'—items frequently bought with alcohol. "
        "Strategic placement of these items can increase the average basket value."
    )
    
    doc.add_heading('Key Affinity Targets', level=2)
    doc.add_paragraph("Based on the Beer & Spirit anchors, common purchase pairings include:")
    for target, weight in data['halo_affinities'].items():
        if target != "Unknown" and target != "Retail Market":
            doc.add_paragraph(f"- {target}", style='List Bullet')
    
    doc.add_paragraph(
        "STRATEGY: Place saline snacks, premium tonics, and citrus fruits (limes) near the exit path of the Alcohol aisle."
    )

    # 6. Conclusion
    doc.add_heading('5. Operational Next Steps', level=1)
    doc.add_paragraph("1. Audit Beer storage capacity to ensure zero out-of-stocks on the Top 10 anchors.")
    doc.add_paragraph("2. Review Wine inventory ages; identify SKUs for delisting.")
    doc.add_paragraph("3. Monitor Spirit security for high-value items (Spirit section shows high inventory value vs volume).")

    report_path = os.path.join(ALCOHOL_DIR, "Alcohol_Operational_Breakdown.docx")
    doc.save(report_path)
    print(f"Report Finalized: {report_path}")

if __name__ == "__main__":
    generate_professional_report()
