"""
O.A.S.I.S. Shadow Report Generator
Phase 2 of the Client Implementation Playbook.

Generates a formal Word document comparing O.A.S.I.S. hypothetical orders
with actual human buyer POs.
"""

import io
import pandas as pd
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

def _styled_para(doc, text, bold=False, italic=False, size=11, color=None, align=None, space_after=6):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold = bold
    run.italic = italic
    run.font.size = Pt(size)
    if color: run.font.color.rgb = color
    if align: p.alignment = align
    p.paragraph_format.space_after = Pt(space_after)
    return p

def _add_table(doc, headers, rows):
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.style = 'Light Shading Accent 1'
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    for i, h in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = h
        for p in cell.paragraphs:
            for r in p.runs:
                r.bold = True
                r.font.size = Pt(9)
    for ri, row in enumerate(rows):
        for ci, val in enumerate(row):
            cell = table.rows[ri+1].cells[ci]
            cell.text = str(val)
            for p in cell.paragraphs:
                for r in p.runs:
                    r.font.size = Pt(9)
    doc.add_paragraph()


def generate_shadow_report(comparison_df: pd.DataFrame, stats: dict):
    """
    Generates a Daily Shadow Comparison Word report.
    Returns BytesIO object.
    """
    doc = Document()
    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(11)

    # Title
    doc.add_paragraph()
    _styled_para(doc, 'O.A.S.I.S. Shadow Mode', bold=True, size=24, align=WD_ALIGN_PARAGRAPH.CENTER, space_after=2)
    _styled_para(doc, f'Daily Comparison Report', bold=True, size=16, color=RGBColor(0x2C, 0x3E, 0x50), align=WD_ALIGN_PARAGRAPH.CENTER)
    _styled_para(doc, f'Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', italic=True, size=11, align=WD_ALIGN_PARAGRAPH.CENTER, space_after=20)

    # Executive Summary
    doc.add_heading('1. Executive Summary', level=1)
    doc.add_paragraph(
        "This report compares the actual Purchase Orders generated by the human procurement team against "
        "the hypothetical (shadow) Purchase Orders generated by the O.A.S.I.S. algorithmic engine for the same period."
    )
    
    _styled_para(doc, 'Summary Statistics:', bold=True, size=12)
    _add_table(doc,
        ['Metric', 'Value'],
        [
            ['Total Line Items Evaluated', str(stats.get('total_line_items', 0))],
            ['Total O.A.S.I.S. Recommended Value', f"KES {stats.get('oasis_total_value', 0):,.2f}"],
            ['Human Over-Order Waste Risk (17% WACC)', f"KES {stats.get('over_order_waste_risk', 0):,.2f}"],
            ['Aligned Orders (Human agreed with O.A.S.I.S.)', str(stats.get('aligned', 0))],
            ['Alignment Accuracy', f"{stats.get('accuracy_pct', 0):.1f}%"],
        ]
    )

    # Critical Divergences
    doc.add_page_break()
    doc.add_heading('2. Critical Divergences', level=1)
    
    # 2.1 Missed Items
    doc.add_heading('2.1 Human Missed - Stockout Risk', level=2)
    doc.add_paragraph(
        f"The human buyer failed to order {stats.get('human_missed', 0)} items that O.A.S.I.S. identified "
        f"as requiring replenishment based on current velocity and lead times. This represents an immediate stockout risk."
    )
    
    missed_df = comparison_df[comparison_df['Divergence'] == 'HUMAN_MISSED']
    if not missed_df.empty:
        missed_rows = []
        for _, row in missed_df.head(20).iterrows():
            missed_rows.append([
                str(row.get('Item_Name', 'N/A'))[:40],
                str(row.get('Shadow_Order_Qty', 0)),
                "0",
                f"KES {row.get('Shadow_Order_Value', 0):,.2f}"
            ])
        _add_table(doc, ['Item Name', 'O.A.S.I.S. Qty', 'Human Qty', 'Value at Risk'], missed_rows)
        if len(missed_df) > 20:
             _styled_para(doc, f"... and {len(missed_df) - 20} more items.", italic=True)

    # 2.2 Over-ordered
    doc.add_heading('2.2 Human Over-Ordered - Dead Stock Risk', level=2)
    doc.add_paragraph(
        f"The human buyer ordered excessively on {stats.get('human_over_ordered', 0)} items compared to the "
        f"algorithmic recommendation. This signifies potential trapped capital and future dead stock. "
        f"Extrapolated Capital Waste (Annualized 17% Holding Cost): KES {stats.get('over_order_waste_risk', 0):,.2f}."
    )

    over_df = comparison_df[comparison_df['Divergence'] == 'HUMAN_OVER_ORDERED']
    if not over_df.empty:
        over_rows = []
        for _, row in over_df.head(20).iterrows():
            over_rows.append([
                str(row.get('Item_Name', 'N/A'))[:40],
                str(row.get('Shadow_Order_Qty', 0)),
                str(row.get('Human_Order_Qty', 0)),
            ])
        _add_table(doc, ['Item Name', 'O.A.S.I.S. (Math) Qty', 'Human (Gut) Qty'], over_rows)
        if len(over_df) > 20:
            _styled_para(doc, f"... and {len(over_df) - 20} more items.", italic=True)

    doc.add_page_break()
    doc.add_heading('3. Remediation', level=1)
    doc.add_paragraph(
        "Transitioning these items to O.A.S.I.S. autonomous management will instantly eliminate both "
        "the stockout risk from missed lines and the capital bloat from human over-ordering."
    )

    output = io.BytesIO()
    doc.save(output)
    output.seek(0)
    return output
